language: java
jdk:
  - oraclejdk7
before_script:
  - echo "create user gitproject@localhost identified by 'gitproject';\ncreate database onlineteach;\ngrant all on onlineteach.* to gitproject;\nflush privileges;\n" | mysql -u root
